### PR TITLE
Some updates to get the example to build and run on Windows.

### PR DESCRIPTION
**Pull request by dradtke**
Trying to build the `allegro-sys` crate was failing because two files only contain a path to another Rust file. Wrapping those paths with the `include!` macro fixes it.

### CODE REVIEW

**Comment by dradtke** [comment]
Hm, it's strange that it failed. It works fine for me when I run `cargo build` locally.

**Comment by SiegeLord** [comment]
A few comments:

- The `include!` macro won't work, as it makes those crates un-publishable (because they refer to a path outside the package directory). I'm not sure what to do just yet, but probably those files should be moved out into a package of their own. It's a bit of an annoyance, to say the least.

- I don't really intend to support non-standard named libraries. I think it's best in this case to either use the link-none feature (and link the libraries manually in your program), or override the linker path via cargo utitilies (see http://doc.crates.io/build-script.html#overriding-build-scripts).

- I was under the impression that `#[thread_local]` worked under Windows... it's surprising that it's still broken.

**Comment by dradtke** [comment]
* Ah, I hadn't realized that the layout of the repo might cause issues with crates.io. In any case, after pulling the code down from Github, I had to update those files to use `include!` in order to get it to build. Creating an `allegro-shared` crate or something might be a good option for getting it to play nicely with both crates.io and Github.

* Hm, I wasn't aware of the Cargo build script override. That approach could work, but would need to be documented somewhere. Maybe I can come up with a stub that just needs to have paths filled in.

* And no, apparently it doesn't. I reported it as [an issue](https://github.com/rust-lang/rust/issues/23672), but it was closed pretty quickly with `thread_local!()` suggested as the workaround.

**Comment by SiegeLord** [comment]
Alright, so I added an `allegro_util` crate to avoid the symlink issue, and cherry-picked your thread_local commit (with some modifications). That should cover everything, yes?

**Comment by SiegeLord** [comment]
I've added some more Windows-related things in f24c4ca64629a4f1669d9b1d3f7b0ef9dbe888ce. Now everything seems to work pretty well on Windows.

**Pull request closed without merging**
